services:
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "/opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "/opt/nginx/html:/usr/share/nginx/html"
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root*123
      TZ: Asia/Shanghai
    volumes:
      - "/opt/mysql/conf:/etc/mysql/conf.d"
      - "/opt/mysql/init:/docker-entrypoint-initdb.d"
      - "/opt/mysql/data:/var/lib/mysql"
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - "/opt/redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "/opt/redis/data:/data"
  nacos:
    image: nacos/nacos-server:v3.0.3
    container_name: nacos
    restart: unless-stopped
    ports:
      - "8848:8848"
      - "18848:8080"
      - "9848:9848"
      - "9849:9849"
    environment:
      MODE: standalone
      TZ: Asia/Shanghai
      JVM_XMS: 128m
      JVM_XMX: 256m
      JVM_XMN: 128m
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_TOKEN: YjJiMmQ5OTQtZDZhYy00ZDE5LTkxMjYtN2I4OTQ4YTVjNTM3
      NACOS_AUTH_IDENTITY_KEY: nacos
      NACOS_AUTH_IDENTITY_VALUE: nacos
    volumes:
      - "/opt/nacos/init:/home/nacos/init.d"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
networks:
  default:
    name: my-network
    driver: bridge